#!/bin/bash
set -e

# Check uncommitted changes.
if [ "$1" != "allow-uncommitted" ]
then
    status="$(git status --porcelain)"
    if [ "$status" != "" ]
    then
        echo "uncommitted changes"
        exit 1
    fi
fi

# Pick a version number.

TAG_NUM=`git tag | grep -Po '(?<=^v0\.)\d+$' | sort -n | tail -n1`
if [ "$TAG_NUM" == "" ]
then
    echo "couldn't find latest tag number"
    exit 1
fi
TAG="v0.$TAG_NUM"

NEW_GH_TAG=0
if gh release view $TAG >/dev/null
then
    TAG_NUM=$(($TAG_NUM + 1))
    TAG="v0.$TAG_NUM"
    NEW_GH_TAG=1
fi

# Write version number to version.rs
BASEDIR=$(dirname "$0")
cat > "$BASEDIR/src/version.rs" <<-EOF
// This file is generated by release.sh
pub const VERSION_STRING: &'static str = "$TAG";
pub const BUILD_TIME: &'static str = "`date +"%Y-%m-%d %H:%M:%S"`";
EOF

# Build.
RUST_BACKTRACE=1 cargo test && cargo build --profile dbgo && cargo build -r

# Copy to my machines.

scp target/x86_64-unknown-linux-musl/dbgo/nnd dev:bin/new-nnd && scp target/x86_64-unknown-linux-musl/release/nnd dev:bin/new-nnd-release && ssh dev 'mv bin/new-nnd bin/nnd; mv bin/new-nnd-release bin/nnd-release;'

cp target/x86_64-unknown-linux-musl/dbgo/nnd ../../nnd-release/nnd-new && mv ../../nnd-release/nnd-new ../../nnd-release/nnd && cp target/x86_64-unknown-linux-musl/release/nnd ../../nnd-release/nnd-release-new && mv ../../nnd-release/nnd-release-new ../../nnd-release/nnd-release

# Push to itch.
butler push target/x86_64-unknown-linux-musl/release/nnd al13n/nnd:linux

# Push to github.

if $NEW_GH_TAG
then
    git tag "$TAG"
    git push origin "$TAG"
fi

cp target/x86_64-unknown-linux-musl/dbgo/nnd nnd-dbgo
trap 'rm nnd-dbgo' EXIT

gh release create "$TAG" --notes "" target/x86_64-unknown-linux-musl/release/nnd nnd-dbgo

echo "all done!"
